### ISSUE TITLE
JS Modules export?

### ISSUE THREAD

**Issue by developit** [blakeembrey/array-flatten#19]
Hi @blakeembrey!

This module is really popular! It's also nice and small, but I was wondering if you'd be open to providing a JS Modules version in addition to CommonJS?  I'd be happy to PR.  Let me know if you have a preference for tooling/etc.

**Comment by blakeembrey** [comment]
@developit Happy to accept a PR 👍

**Comment by blakeembrey** [comment]
Added with https://github.com/blakeembrey/array-flatten/releases/tag/v3.0.0.

**Comment by Lohdro** [comment]
@blakeembrey This breaks existing usage code for the old CommonJS pattern, just as an FYI.
Where `var flatten = require('array-flatten');` used to return the function directly, it now returns an object with the function defined as the object's `flatten` property. Existing calls to the flatten function directly need to be changed to call the method on the returned object instead. Otherwise seeing "Warning: flatten is not a function" error.

Not sure if there is a way to accommodate both usage patterns, or if packages using the old version need to either update or manually specify the older version of this package as a dependency, but I think a lot of people will have builds that break due to this. (grunt-assemble is affected)

**Comment by blakeembrey** [comment]
I know, that’s why this was released as V3. If it affects anything, they’re using dependencies incorrectly.

**Comment by blakeembrey** [comment]
I also don’t see this used in grunt assemble either.

**Comment by Lohdro** [comment]
@blakeembrey Thanks for taking the time to reply to my comment. I tracked the issue to this package from grunt-assemble > resolve-dep > arrayify-compact > array-flatten

Admittedly some of the versions of those packages that were in use on my affected project are 4+ years old and it's likely that there are issues with dependency management somewhere in that tree. I was able to fix the issue on my end by adding version 2.1.2 of your module as a dependency in my package.json, even though I'm not using it directly in my build.

[arrayify-compact](https://github.com/jonschlinkert/arrayify-compact/blob/master/package.json#L30) lists version 1.0.1 as a dependency but appears to have been pulling in the latest version instead.

Didn't mean to imply there was an issue on your end, just wanted to point that out in case anyone else came across the same problem. Thanks again!
